# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - notetoself-bun

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4      

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build application
        run: bun build ./src/index.tsx --outdir dist --target bun

      - name: Download Bun runtime for deployment
        run: |
          curl -fsSL https://bun.sh/install | bash
          mkdir -p runtime
          cp ~/.bun/bin/bun runtime/bun
          chmod +x runtime/bun

      - name: Prepare deployment folder
        run: |
          rm -rf deploy
          mkdir deploy
          cp -a static/. dist/static
          cp -R dist/. deploy
          cp package.json deploy/
          cp -R node_modules deploy/
          cp runtime/bun deploy/bun
          ls -al deploy

      - name: Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: bun-hono-deploy
          path: deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: bun-hono-deploy
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_323D499DEF3C4D34BF8FB8E157CE4647 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D5FB115B4C5E4DABB9CE6B4B06BA1730 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_89BD3C841BD64EF7B67045FA75388073 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'notetoself-bun'
          slot-name: 'Production'
          package: .
          